[viewer]
    Title = "LorraineWen的博客网站"
    Description = "LorraineWen的博客网站"
    Logo = "http://localhost:8080/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "http://localhost:8080/resource/images/avatar.jpg"
    UserName = "LorraineWen"
    UserDesc = "A common programmer"
#这些都必须替换为自己的
[system]
    CdnURL = "http://localhost:8080/resource"
    QiniuAccessKey = "wUZJoUslBlE4inCH9NlXmdckMxdIKM4OC7YSXywE"
    QiniuSecretKey = "4yAsxNtf--2XI3eW37SXlxWqJ4Jx0_xdd857Ys8U"
    Valine = true
    ValineAppid = "NWzqA3j31TJpfOuzvkU1VF1b-gzGzoHsz"
    ValineAppkey = "zd6wwPn20KKDzUKjoxQifDKK"
    ValineServerURL = "https://nwzqa3j3.lc-cn-n1-shared.com"